spring:
  application:
    name: order-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          predicates:
          - Path= /api/account-service/**
          uri: lb://account-service
        - id: inventory-service
          predicates:
            - Path= /api/inventory-service/**
          uri: lb://inventory-service
        - id: order-service
          predicates:
            - Path= /api/order-service/**
          uri: lb://order-service
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka